CREATE TABLE CUSTOMER (
		customerid INTEGER NOT NULL,
		title CHAR(3) NOT NULL,
		firstname VARCHAR(30) NOT NULL,
		lastname VARCHAR(30) NOT NULL,
		userid CHAR(8),
		password CHAR(8)
	);

CREATE UNIQUE INDEX IDX_CUSTOMER ON CUSTOMER (customerid ASC);

ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (customerid);

--//@UNDO

DROP TABLE CUSTOMER;