CREATE TABLE TRANSRECORD (
        transid TIMESTAMP NOT NULL,
        accid CHAR(8) NOT NULL,
        transtype CHAR(1) NOT NULL,
        transamt DECIMAL(10, 2) NOT NULL
	);

CREATE UNIQUE INDEX IDX_TRANSRECORD ON TRANSRECORD (transid ASC);

ALTER TABLE TRANSRECORD ADD CONSTRAINT PK_TRANSID PRIMARY KEY (transid);

ALTER TABLE TRANSRECORD ADD CONSTRAINT FK_ACC_TO_TRANSREC FOREIGN KEY (accid)
	REFERENCES ACCOUNT (accid);

--//@UNDO

DROP TABLE TRANSRECORD;