CREATE TABLE CUSTACCT (
		customerid INTEGER NOT NULL,
		accid CHAR(8) NOT NULL
	);

CREATE UNIQUE INDEX IDX_CUSTACCT ON CUSTACCT (customerid ASC, accid ASC);

ALTER TABLE CUSTACCT ADD CONSTRAINT PK_CUSTACCT PRIMARY KEY (customerid, accid);

ALTER TABLE CUSTACCT ADD CONSTRAINT FK_CA_TO_CUST FOREIGN KEY (customerid, accid)
	REFERENCES CUSTACCT (customerid, accid);

--//@UNDO

DROP TABLE CUSTACCT;