CREATE TABLE CUSTACCT (
        customerid INTEGER NOT NULL,
        accid CHAR(8) NOT NULL,
	CONSTRAINT PK_CUSTACCT PRIMARY KEY (customerid, accid)
    );

ALTER TABLE CUSTACCT ADD CONSTRAINT FK_CA_TO_CUST FOREIGN KEY (customerid, accid)
    REFERENCES CUSTACCT (customerid, accid) ON DELETE CASCADE;

--//@UNDO

DROP TABLE CUSTACCT;
