ALTER TABLE CUSTOMER ALTER COLUMN userid SET NOT NULL;
ALTER TABLE CUSTOMER ALTER COLUMN password SET NOT NULL;

--//@UNDO

ALTER TABLE CUSTOMER ALTER COLUMN userid SET NULL;
ALTER TABLE CUSTOMER ALTER COLUMN password SET NULL;
